//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadageSportsDb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public long MatchId { get; set; }
        public Nullable<int> HomeTeamId { get; set; }
        public Nullable<int> AwayTeamId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> RoundId { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
    
        public virtual AwayTeam AwayTeam { get; set; }
        public virtual HomeTeam HomeTeam { get; set; }
        public virtual Round Round { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
