//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BroadageSportsDb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Score()
        {
            this.AwayTeam = new HashSet<AwayTeam>();
            this.HomeTeam = new HashSet<HomeTeam>();
        }
    
        public int ScoreId { get; set; }
        public Nullable<int> Regular { get; set; }
        public Nullable<int> HalfTime { get; set; }
        public Nullable<int> Current { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AwayTeam> AwayTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeTeam> HomeTeam { get; set; }
    }
}
